#!/bin/bash
# Screenshot commands for backup demo materials

echo "📸 Take these screenshots for your backup demo:"
echo ""
echo "1. System Status:"
echo "   Command: bash status.sh"
echo "   Save as: screenshots/01_system_status.png"
echo ""
echo "2. Completed Tasks:"
echo "   Command: ls -lh Done/"
echo "   Save as: screenshots/02_completed_tasks.png"
echo ""
echo "3. Execution Log Example:"
echo "   Command: cat Logs/demo_email_signature.md.execution.log"
echo "   Save as: screenshots/03_execution_log.png"
echo ""
echo "4. Cron Jobs:"
echo "   Command: crontab -l"
echo "   Save as: screenshots/04_cron_automation.png"
echo ""
echo "5. LinkedIn Posts:"
echo "   Open your LinkedIn profile in browser"
echo "   Save as: screenshots/05_linkedin_posts.png"
echo ""
echo "6. Gmail Watcher Running:"
echo "   Command: ps aux | grep gmail_watcher"
echo "   Save as: screenshots/06_gmail_watcher.png"
echo ""
echo "7. Task History:"
echo "   Command: cat Memory/task_history.json | jq '.tasks[-5:]'"
echo "   Save as: screenshots/07_task_history.png"
echo ""

mkdir -p screenshots
echo "✅ Created screenshots/ directory"
echo ""
echo "Run each command and take a screenshot!"
