#!/bin/bash
# Test Gmail Watcher Flow

echo "🧪 Gmail Watcher Test Flow"
echo "=========================="
echo ""
echo "Step 1: Start the watcher in one terminal"
echo "  cd /home/sk/projects/hacahthoon-0/personal-ai-employee/AI_Employee_Vault"
echo "  source venv/bin/activate"
echo "  python watchers/gmail_watcher.py"
echo ""
echo "Step 2: In Claude Code (another terminal), send email:"
echo "  Send an email to sc3078745@gmail.com with subject 'Test $(date +%H:%M)'"
echo "  and body 'Testing watcher detection at $(date)'"
echo ""
echo "Step 3: Watch the watcher terminal - within 2 minutes you'll see:"
echo "  ✅ Processed 1 new email(s)"
echo "  📧 Created task from email: Test XX:XX"
echo ""
echo "Step 4: Check the file was created:"
echo "  ls -lh Needs_Action/EMAIL_Test*"
echo ""
echo "Step 5: View the task file:"
echo "  cat Needs_Action/EMAIL_Test*.md"
echo ""
